# Generated by Django 4.2.4 on 2023-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_alter_mesas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='estado',
            field=models.CharField(choices=[('Ocupada', 'Ocupada'), ('Libre', 'Libre')], default='Libre', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
