# Generated by Django 4.2.4 on 2023-11-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_comanda_estado_alter_mesas_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'ordering': ['nombre', 'descripcion'], 'verbose_name': 'TipoUsuario', 'verbose_name_plural': 'TipoUsuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['nombre', 'apellido', 'rut', 'email', 'password', 'password2', 'telefono', 'tipoUsuario', 'estado'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='tipousuario',
            name='estado',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
