# Generated by Django 4.2.4 on 2023-11-20 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0008_userprofile_remove_usuarios_tipousuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallecomanda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mesas',
            options={'ordering': ['numero'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mesas',
            name='estado',
        ),
        migrations.AddField(
            model_name='comanda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecomanda',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
