# Generated by Django 4.2.4 on 2023-11-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiendaApp', '0008_usuarios_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['nombre', 'apellido', 'rut', 'telefono', 'tipoUsuario', 'estado'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password2',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
