# Generated by Django 4.2.4 on 2023-12-11 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiendaApp', '0009_alter_comanda_options_alter_detallecomanda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
